name: Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

permissions:
  contents: read
  actions: write

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --no-scripts --optimize-autoloader

      - name: Install npm dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Pre-flight checks
        run: |
          echo "🔍 Pre-flight validation..."
          php -l gsap-block-animator.php || { echo "❌ Main file syntax error"; exit 1; }
          [ -f includes/autoloader.php ] || { echo "❌ Autoloader missing"; exit 1; }
          [ -f includes/plugin.php ] || { echo "❌ Plugin class missing"; exit 1; }
          echo "✅ Basic validation passed"

      - name: Verify wp-env configuration
        run: |
          echo "📋 wp-env.json configuration:"
          cat .wp-env.json
          echo ""

      - name: Setup WordPress environment
        timeout-minutes: 3
        run: |
          npm install -g @wordpress/env
          echo "🚀 Starting WordPress environment..."
          
          # Start wp-env with timeout protection
          timeout 150 npx wp-env start --config=.wp-env.json || {
            echo "❌ WordPress start timed out, checking logs..."
            npx wp-env logs || echo "No logs available"
            exit 1
          }
          
          echo "✅ WordPress environment started"
          echo "⏱️ Waiting for services to stabilize..."
          sleep 5

      - name: Wait for WordPress to be ready
        timeout-minutes: 2
        run: |
          echo "🔍 Waiting for WordPress to respond..."
          timeout 120 bash -c 'until curl -s http://localhost:8888 >/dev/null; do echo "Waiting..."; sleep 2; done'
          echo "✅ WordPress is responding"

      - name: Debug plugin files
        timeout-minutes: 1
        run: |
          echo "📋 Quick plugin checks:"
          [ -f vendor/autoload.php ] && echo "✅ Autoloader exists" || echo "❌ Autoloader missing"
          [ -d includes ] && echo "✅ Includes directory exists" || echo "❌ Includes missing"
          npx wp-env run cli test -f /var/www/html/wp-content/plugins/gsap-block-animator/gsap-block-animator.php && echo "✅ Plugin file in WordPress" || echo "❌ Plugin file missing"

      - name: Setup WordPress and plugin
        timeout-minutes: 2
        run: |
          echo "🔍 Verifying WordPress..."
          npx wp-env run cli wp core is-installed || { echo "❌ WordPress not ready"; exit 1; }
          
          echo "🔌 Activating plugin..."
          if ! timeout 60 npx wp-env run cli wp plugin activate gsap-block-animator 2>&1; then
            echo "❌ Plugin activation failed"
            echo "📋 Debug logs:"
            npx wp-env run cli wp plugin status gsap-block-animator 2>/dev/null || echo "Plugin status unavailable"
            npx wp-env run cli cat /var/www/html/wp-content/debug.log 2>/dev/null | tail -20 || echo "No debug.log"
            exit 1
          fi
          
          echo "✅ Plugin activated"

      - name: Setup Playwright
        timeout-minutes: 3
        working-directory: ./tests/playwright
        run: |
          echo "Installing Playwright dependencies..."
          npm install
          echo "Installing Playwright browsers..."
          npx playwright install chromium
          echo "Playwright setup complete"

      - name: Run Playwright tests
        id: playwright-tests
        timeout-minutes: 10
        working-directory: ./tests/playwright
        env:
          CI: true
          PLAYWRIGHT_BASE_URL: http://localhost:8888
        run: |
          echo "Base URL: $PLAYWRIGHT_BASE_URL"
          echo "WordPress status check:"
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8888 || echo "WordPress not responding"
          
          echo "Starting Playwright tests..."
          npx playwright test --reporter=list,html --timeout=30000
          test_exit_code=$?
          echo "exit_code=$test_exit_code" >> $GITHUB_OUTPUT
          
          if [ $test_exit_code -ne 0 ]; then
            echo "Tests failed with exit code $test_exit_code"
            exit $test_exit_code
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: tests/playwright/test-results/
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          if-no-files-found: ignore
          retention-days: 7

      - name: Check test results
        if: steps.playwright-tests.outcome == 'failure'
        run: |
          echo "❌ Playwright tests failed!"
          exit 1

      - name: Stop WordPress environment
        if: always()
        run: npx wp-env stop