name: Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

permissions:
  contents: read
  actions: write

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --no-scripts --optimize-autoloader

      - name: Install npm dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Verify wp-env configuration
        run: |
          echo "📋 wp-env.json configuration:"
          cat .wp-env.json
          echo ""

      - name: Setup WordPress environment
        timeout-minutes: 5
        run: |
          npm install -g @wordpress/env
          echo "🚀 Starting WordPress environment..."
          npx wp-env start --config=.wp-env.json
          echo "📊 WordPress container status:"
          npx wp-env run cli wp --info
          echo "⏱️ Waiting for WordPress to fully initialize..."
          sleep 10

      - name: Wait for WordPress to be ready
        timeout-minutes: 2
        run: |
          echo "🔍 Waiting for WordPress to respond..."
          timeout 120 bash -c 'until curl -s http://localhost:8888 >/dev/null; do echo "Waiting..."; sleep 2; done'
          echo "✅ WordPress is responding"

      - name: Debug plugin files
        run: |
          echo "📁 Plugin directory structure:"
          ls -la /home/runner/work/gsap-block-animator/gsap-block-animator/
          echo ""
          echo "📁 Plugin includes directory:"
          ls -la /home/runner/work/gsap-block-animator/gsap-block-animator/includes/ || echo "Includes directory not found"
          echo ""
          echo "📁 Plugin vendor directory:"
          ls -la /home/runner/work/gsap-block-animator/gsap-block-animator/vendor/ || echo "Vendor directory not found"
          echo ""
          echo "📋 Composer autoloader check:"
          [ -f /home/runner/work/gsap-block-animator/gsap-block-animator/vendor/autoload.php ] && echo "✅ Composer autoloader exists" || echo "❌ Composer autoloader missing"
          echo ""
          echo "📁 WordPress plugins directory:"
          npx wp-env run cli ls -la /var/www/html/wp-content/plugins/gsap-block-animator/ || echo "Plugin not found in WordPress"
          echo ""
          echo "📋 Plugin main file in WordPress:"
          npx wp-env run cli test -f /var/www/html/wp-content/plugins/gsap-block-animator/gsap-block-animator.php && echo "✅ Main plugin file exists" || echo "❌ Main plugin file missing"
          echo ""
          echo "🔍 Testing PHP syntax in WordPress environment:"
          npx wp-env run cli php -l /var/www/html/wp-content/plugins/gsap-block-animator/gsap-block-animator.php || echo "❌ PHP syntax error in main file"

      - name: Setup WordPress and plugin
        timeout-minutes: 3
        run: |
          echo "🔍 Verifying WordPress installation..."
          npx wp-env run cli wp core is-installed || (echo "❌ WordPress not installed" && exit 1)
          
          echo "📋 Available plugins before activation:"
          npx wp-env run cli wp plugin list
          echo ""
          
          echo "🔌 Attempting to activate plugin..."
          if ! npx wp-env run cli wp plugin activate gsap-block-animator; then
            echo "❌ Plugin activation failed. Getting error logs..."
            echo "📋 WordPress error log:"
            npx wp-env run cli cat /var/www/html/wp-content/debug.log 2>/dev/null || echo "No debug.log found"
            echo ""
            echo "📋 WordPress environment logs:"
            npx wp-env logs
            echo ""
            echo "📋 Plugin status:"
            npx wp-env run cli wp plugin status gsap-block-animator || echo "Plugin status unavailable"
            exit 1
          fi
          
          echo "✅ Plugin activated successfully"
          echo "📋 Active plugins:"
          npx wp-env run cli wp plugin list --status=active
          echo "✅ WordPress setup complete"

      - name: Setup Playwright
        timeout-minutes: 3
        working-directory: ./tests/playwright
        run: |
          echo "Installing Playwright dependencies..."
          npm install
          echo "Installing Playwright browsers..."
          npx playwright install chromium
          echo "Playwright setup complete"

      - name: Run Playwright tests
        id: playwright-tests
        timeout-minutes: 10
        working-directory: ./tests/playwright
        env:
          CI: true
          PLAYWRIGHT_BASE_URL: http://localhost:8888
        run: |
          echo "Base URL: $PLAYWRIGHT_BASE_URL"
          echo "WordPress status check:"
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8888 || echo "WordPress not responding"
          
          echo "Starting Playwright tests..."
          npx playwright test --reporter=list,html --timeout=30000
          test_exit_code=$?
          echo "exit_code=$test_exit_code" >> $GITHUB_OUTPUT
          
          if [ $test_exit_code -ne 0 ]; then
            echo "Tests failed with exit code $test_exit_code"
            exit $test_exit_code
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: tests/playwright/test-results/
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          if-no-files-found: ignore
          retention-days: 7

      - name: Check test results
        if: steps.playwright-tests.outcome == 'failure'
        run: |
          echo "❌ Playwright tests failed!"
          exit 1

      - name: Stop WordPress environment
        if: always()
        run: npx wp-env stop